### ISSUE TITLE
Does not work with Gravity Forms

### ISSUE THREAD

**Issue by raftaar1191** [Ziggeo/ziggeo-video-for-gravity-forms#1]
I tried to run the plugin with Gravity forms Version 2.4.17 but it does not seem to be working

**Comment by Bane-D** [comment]
Hi Deepak,

I am doing final rounds of testing and will be releasing new codes. I have to update the core plugin on Wordpress first because the new code of this plugin is based on some new changes in our core plugin.

Still if you see some errors or have info that you can tell me please post here so I can test against that and make sure that new code has the fix for the same ready if not already in there.

Thanks,
Bane

**Comment by raftaar1191** [comment]
Suggestion when we are activating this plugin without the main plugin it should through an  error

https://github.com/Ziggeo/ziggeo-wordpress-plugin

**Comment by Bane-D** [comment]
Hi Deepak,

Makes sense. Thank you for the suggestion. Will add the same.

Regards,
Bane
